site_name: 'SSO Kepri Documentation'
site_description: 'Single Sign-On (SSO) Kepri Usage Documentation'
site_author: 'KIIS Kominfo Kepri'
docs_dir: docs/
repo_name: 'kiiskominfokepri/sso-kepri-documentation'
repo_url: https://github.com/kiiskominfokepri/sso-kepri-documentation
theme:  
  name: material
  # custom_dir: overrides
  features:
    - content.code.copy  
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
nav:
  - Home: index.md
  - OIDC Scopes: scopes.md
  - Endpoints: endpoints.md
  - Client Registration: client-registration.md
  - Server-Side Apps: server-side-apps.md
  - Mobile & Native Apps: mobile-and-native-apps.md
  - License: license.md
  - About: about.md
markdown_extensions:
  - pymdownx.highlight:
      extend_pygments_lang:
        - name: php
          lang: php
          options:
            startinline: true
        - name: pycon3
          lang: pycon
          options:
            python3: true
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite: